x-common-variables: &common-variables
  ENV: local
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  web:
    build: 
      context: process/sp
      dockerfile: Dockerfile
    container_name: "web"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./process/sp/app:/code
    env_file:
      .env  
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      <<: *common-variables

volumes:
  postgres_data:
    driver: local